# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-26 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='number',
            field=models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=6, null=True),
        ),
    ]
