# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-26 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0003_auto_20200126_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='number',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
    ]
