# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-10 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='artist',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='artists.Artist'),
        ),
    ]
