# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-17 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('records', '0003_record_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='genre',
        ),
        migrations.AddField(
            model_name='record',
            name='genre',
            field=models.ManyToManyField(to='genres.Genre'),
        ),
    ]
