# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-17 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('records', '0004_auto_20200117_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='genre',
        ),
        migrations.AddField(
            model_name='record',
            name='genre',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='genres.Genre'),
        ),
    ]
