# Generated by Django 3.0.2 on 2020-01-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='number',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
    ]
